/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    "introduction",
    "getting-started",
    {
      type: "category",
      label: "Using Phero",
      items: [
        "using-phero/creating-the-server",
        "using-phero/using-the-client",
        "using-phero/error-handling",
        "using-phero/context-and-middleware",
        "using-phero/cors",
      ],
    },
    {
      type: "category",
      label: "Integration guides",
      items: [
        { type: "doc", label: "Phero with React", id: "integration/react" },
      ],
    },
    {
      type: "category",
      label: "Deploying Phero",
      items: [
        { type: "doc", label: "NodeJS", id: "deploying-phero/nodejs" },
        {
          type: "doc",
          label: "GCloud functions",
          id: "deploying-phero/gcloud-functions",
        },
        { type: "doc", label: "Vercel", id: "deploying-phero/vercel" },
      ],
    },
    // {type: 'autogenerated', dirName: '.'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

module.exports = sidebars
